apiVersion: v1
kind: ServiceAccount
metadata:
  name: fuse-csi-node
  namespace: fuse-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fuse-csi-node
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fuse-csi-node
subjects:
  - kind: ServiceAccount
    name: fuse-csi-node
    namespace: fuse-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: fuse-csi-node
