apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: fuse.csi.storage.io
spec:
  attachRequired: false
  podInfoOnMount: true
  fsGroupPolicy: None
  volumeLifecycleModes:
    - Ephemeral
    - Persistent
