// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v6.33.4
// source: coordinator.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	CoordinatorService_RegisterPeer_FullMethodName       = "/pb.CoordinatorService/RegisterPeer"
	CoordinatorService_GetPeers_FullMethodName           = "/pb.CoordinatorService/GetPeers"
	CoordinatorService_UpdatePeerStatus_FullMethodName   = "/pb.CoordinatorService/UpdatePeerStatus"
	CoordinatorService_GetFileLocation_FullMethodName    = "/pb.CoordinatorService/GetFileLocation"
	CoordinatorService_UpdateFileLocation_FullMethodName = "/pb.CoordinatorService/UpdateFileLocation"
	CoordinatorService_GetPeerStats_FullMethodName       = "/pb.CoordinatorService/GetPeerStats"
)

// CoordinatorServiceClient is the client API for CoordinatorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CoordinatorServiceClient interface {
	RegisterPeer(ctx context.Context, in *RegisterPeerRequest, opts ...grpc.CallOption) (*RegisterPeerResponse, error)
	GetPeers(ctx context.Context, in *GetPeersRequest, opts ...grpc.CallOption) (*GetPeersResponse, error)
	UpdatePeerStatus(ctx context.Context, in *UpdatePeerStatusRequest, opts ...grpc.CallOption) (*UpdatePeerStatusResponse, error)
	GetFileLocation(ctx context.Context, in *GetFileLocationRequest, opts ...grpc.CallOption) (*GetFileLocationResponse, error)
	UpdateFileLocation(ctx context.Context, in *UpdateFileLocationRequest, opts ...grpc.CallOption) (*UpdateFileLocationResponse, error)
	GetPeerStats(ctx context.Context, in *GetPeerStatsRequest, opts ...grpc.CallOption) (*GetPeerStatsResponse, error)
}

type coordinatorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCoordinatorServiceClient(cc grpc.ClientConnInterface) CoordinatorServiceClient {
	return &coordinatorServiceClient{cc}
}

func (c *coordinatorServiceClient) RegisterPeer(ctx context.Context, in *RegisterPeerRequest, opts ...grpc.CallOption) (*RegisterPeerResponse, error) {
	out := new(RegisterPeerResponse)
	err := c.cc.Invoke(ctx, CoordinatorService_RegisterPeer_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinatorServiceClient) GetPeers(ctx context.Context, in *GetPeersRequest, opts ...grpc.CallOption) (*GetPeersResponse, error) {
	out := new(GetPeersResponse)
	err := c.cc.Invoke(ctx, CoordinatorService_GetPeers_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinatorServiceClient) UpdatePeerStatus(ctx context.Context, in *UpdatePeerStatusRequest, opts ...grpc.CallOption) (*UpdatePeerStatusResponse, error) {
	out := new(UpdatePeerStatusResponse)
	err := c.cc.Invoke(ctx, CoordinatorService_UpdatePeerStatus_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinatorServiceClient) GetFileLocation(ctx context.Context, in *GetFileLocationRequest, opts ...grpc.CallOption) (*GetFileLocationResponse, error) {
	out := new(GetFileLocationResponse)
	err := c.cc.Invoke(ctx, CoordinatorService_GetFileLocation_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinatorServiceClient) UpdateFileLocation(ctx context.Context, in *UpdateFileLocationRequest, opts ...grpc.CallOption) (*UpdateFileLocationResponse, error) {
	out := new(UpdateFileLocationResponse)
	err := c.cc.Invoke(ctx, CoordinatorService_UpdateFileLocation_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinatorServiceClient) GetPeerStats(ctx context.Context, in *GetPeerStatsRequest, opts ...grpc.CallOption) (*GetPeerStatsResponse, error) {
	out := new(GetPeerStatsResponse)
	err := c.cc.Invoke(ctx, CoordinatorService_GetPeerStats_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CoordinatorServiceServer is the server API for CoordinatorService service.
// All implementations must embed UnimplementedCoordinatorServiceServer
// for forward compatibility
type CoordinatorServiceServer interface {
	RegisterPeer(context.Context, *RegisterPeerRequest) (*RegisterPeerResponse, error)
	GetPeers(context.Context, *GetPeersRequest) (*GetPeersResponse, error)
	UpdatePeerStatus(context.Context, *UpdatePeerStatusRequest) (*UpdatePeerStatusResponse, error)
	GetFileLocation(context.Context, *GetFileLocationRequest) (*GetFileLocationResponse, error)
	UpdateFileLocation(context.Context, *UpdateFileLocationRequest) (*UpdateFileLocationResponse, error)
	GetPeerStats(context.Context, *GetPeerStatsRequest) (*GetPeerStatsResponse, error)
	mustEmbedUnimplementedCoordinatorServiceServer()
}

// UnimplementedCoordinatorServiceServer must be embedded to have forward compatible implementations.
type UnimplementedCoordinatorServiceServer struct {
}

func (UnimplementedCoordinatorServiceServer) RegisterPeer(context.Context, *RegisterPeerRequest) (*RegisterPeerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterPeer not implemented")
}
func (UnimplementedCoordinatorServiceServer) GetPeers(context.Context, *GetPeersRequest) (*GetPeersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPeers not implemented")
}
func (UnimplementedCoordinatorServiceServer) UpdatePeerStatus(context.Context, *UpdatePeerStatusRequest) (*UpdatePeerStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePeerStatus not implemented")
}
func (UnimplementedCoordinatorServiceServer) GetFileLocation(context.Context, *GetFileLocationRequest) (*GetFileLocationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFileLocation not implemented")
}
func (UnimplementedCoordinatorServiceServer) UpdateFileLocation(context.Context, *UpdateFileLocationRequest) (*UpdateFileLocationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateFileLocation not implemented")
}
func (UnimplementedCoordinatorServiceServer) GetPeerStats(context.Context, *GetPeerStatsRequest) (*GetPeerStatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPeerStats not implemented")
}
func (UnimplementedCoordinatorServiceServer) mustEmbedUnimplementedCoordinatorServiceServer() {}

// UnsafeCoordinatorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CoordinatorServiceServer will
// result in compilation errors.
type UnsafeCoordinatorServiceServer interface {
	mustEmbedUnimplementedCoordinatorServiceServer()
}

func RegisterCoordinatorServiceServer(s grpc.ServiceRegistrar, srv CoordinatorServiceServer) {
	s.RegisterService(&CoordinatorService_ServiceDesc, srv)
}

func _CoordinatorService_RegisterPeer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterPeerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinatorServiceServer).RegisterPeer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoordinatorService_RegisterPeer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinatorServiceServer).RegisterPeer(ctx, req.(*RegisterPeerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoordinatorService_GetPeers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPeersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinatorServiceServer).GetPeers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoordinatorService_GetPeers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinatorServiceServer).GetPeers(ctx, req.(*GetPeersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoordinatorService_UpdatePeerStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePeerStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinatorServiceServer).UpdatePeerStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoordinatorService_UpdatePeerStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinatorServiceServer).UpdatePeerStatus(ctx, req.(*UpdatePeerStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoordinatorService_GetFileLocation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFileLocationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinatorServiceServer).GetFileLocation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoordinatorService_GetFileLocation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinatorServiceServer).GetFileLocation(ctx, req.(*GetFileLocationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoordinatorService_UpdateFileLocation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateFileLocationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinatorServiceServer).UpdateFileLocation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoordinatorService_UpdateFileLocation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinatorServiceServer).UpdateFileLocation(ctx, req.(*UpdateFileLocationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoordinatorService_GetPeerStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPeerStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinatorServiceServer).GetPeerStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoordinatorService_GetPeerStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinatorServiceServer).GetPeerStats(ctx, req.(*GetPeerStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CoordinatorService_ServiceDesc is the grpc.ServiceDesc for CoordinatorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CoordinatorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.CoordinatorService",
	HandlerType: (*CoordinatorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterPeer",
			Handler:    _CoordinatorService_RegisterPeer_Handler,
		},
		{
			MethodName: "GetPeers",
			Handler:    _CoordinatorService_GetPeers_Handler,
		},
		{
			MethodName: "UpdatePeerStatus",
			Handler:    _CoordinatorService_UpdatePeerStatus_Handler,
		},
		{
			MethodName: "GetFileLocation",
			Handler:    _CoordinatorService_GetFileLocation_Handler,
		},
		{
			MethodName: "UpdateFileLocation",
			Handler:    _CoordinatorService_UpdateFileLocation_Handler,
		},
		{
			MethodName: "GetPeerStats",
			Handler:    _CoordinatorService_GetPeerStats_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "coordinator.proto",
}
