// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v6.33.4
// source: peer.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	PeerService_ReadFile_FullMethodName   = "/pb.PeerService/ReadFile"
	PeerService_WriteFile_FullMethodName  = "/pb.PeerService/WriteFile"
	PeerService_DeleteFile_FullMethodName = "/pb.PeerService/DeleteFile"
	PeerService_FileExists_FullMethodName = "/pb.PeerService/FileExists"
	PeerService_FileSize_FullMethodName   = "/pb.PeerService/FileSize"
)

// PeerServiceClient is the client API for PeerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PeerServiceClient interface {
	// ReadFile streams file data back in 64KB chunks.
	ReadFile(ctx context.Context, in *ReadFileRequest, opts ...grpc.CallOption) (PeerService_ReadFileClient, error)
	// WriteFile receives metadata + data chunks via client streaming.
	WriteFile(ctx context.Context, opts ...grpc.CallOption) (PeerService_WriteFileClient, error)
	// DeleteFile removes a file from this peer's local storage.
	DeleteFile(ctx context.Context, in *DeleteFileRequest, opts ...grpc.CallOption) (*DeleteFileResponse, error)
	// FileExists checks if a file exists on this peer.
	FileExists(ctx context.Context, in *FileExistsRequest, opts ...grpc.CallOption) (*FileExistsResponse, error)
	// FileSize returns the size of a file on this peer.
	FileSize(ctx context.Context, in *FileSizeRequest, opts ...grpc.CallOption) (*FileSizeResponse, error)
}

type peerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPeerServiceClient(cc grpc.ClientConnInterface) PeerServiceClient {
	return &peerServiceClient{cc}
}

func (c *peerServiceClient) ReadFile(ctx context.Context, in *ReadFileRequest, opts ...grpc.CallOption) (PeerService_ReadFileClient, error) {
	stream, err := c.cc.NewStream(ctx, &PeerService_ServiceDesc.Streams[0], PeerService_ReadFile_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &peerServiceReadFileClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type PeerService_ReadFileClient interface {
	Recv() (*FileChunk, error)
	grpc.ClientStream
}

type peerServiceReadFileClient struct {
	grpc.ClientStream
}

func (x *peerServiceReadFileClient) Recv() (*FileChunk, error) {
	m := new(FileChunk)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *peerServiceClient) WriteFile(ctx context.Context, opts ...grpc.CallOption) (PeerService_WriteFileClient, error) {
	stream, err := c.cc.NewStream(ctx, &PeerService_ServiceDesc.Streams[1], PeerService_WriteFile_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &peerServiceWriteFileClient{stream}
	return x, nil
}

type PeerService_WriteFileClient interface {
	Send(*WriteFileRequest) error
	CloseAndRecv() (*WriteFileResponse, error)
	grpc.ClientStream
}

type peerServiceWriteFileClient struct {
	grpc.ClientStream
}

func (x *peerServiceWriteFileClient) Send(m *WriteFileRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *peerServiceWriteFileClient) CloseAndRecv() (*WriteFileResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(WriteFileResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *peerServiceClient) DeleteFile(ctx context.Context, in *DeleteFileRequest, opts ...grpc.CallOption) (*DeleteFileResponse, error) {
	out := new(DeleteFileResponse)
	err := c.cc.Invoke(ctx, PeerService_DeleteFile_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *peerServiceClient) FileExists(ctx context.Context, in *FileExistsRequest, opts ...grpc.CallOption) (*FileExistsResponse, error) {
	out := new(FileExistsResponse)
	err := c.cc.Invoke(ctx, PeerService_FileExists_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *peerServiceClient) FileSize(ctx context.Context, in *FileSizeRequest, opts ...grpc.CallOption) (*FileSizeResponse, error) {
	out := new(FileSizeResponse)
	err := c.cc.Invoke(ctx, PeerService_FileSize_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PeerServiceServer is the server API for PeerService service.
// All implementations must embed UnimplementedPeerServiceServer
// for forward compatibility
type PeerServiceServer interface {
	// ReadFile streams file data back in 64KB chunks.
	ReadFile(*ReadFileRequest, PeerService_ReadFileServer) error
	// WriteFile receives metadata + data chunks via client streaming.
	WriteFile(PeerService_WriteFileServer) error
	// DeleteFile removes a file from this peer's local storage.
	DeleteFile(context.Context, *DeleteFileRequest) (*DeleteFileResponse, error)
	// FileExists checks if a file exists on this peer.
	FileExists(context.Context, *FileExistsRequest) (*FileExistsResponse, error)
	// FileSize returns the size of a file on this peer.
	FileSize(context.Context, *FileSizeRequest) (*FileSizeResponse, error)
	mustEmbedUnimplementedPeerServiceServer()
}

// UnimplementedPeerServiceServer must be embedded to have forward compatible implementations.
type UnimplementedPeerServiceServer struct {
}

func (UnimplementedPeerServiceServer) ReadFile(*ReadFileRequest, PeerService_ReadFileServer) error {
	return status.Errorf(codes.Unimplemented, "method ReadFile not implemented")
}
func (UnimplementedPeerServiceServer) WriteFile(PeerService_WriteFileServer) error {
	return status.Errorf(codes.Unimplemented, "method WriteFile not implemented")
}
func (UnimplementedPeerServiceServer) DeleteFile(context.Context, *DeleteFileRequest) (*DeleteFileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteFile not implemented")
}
func (UnimplementedPeerServiceServer) FileExists(context.Context, *FileExistsRequest) (*FileExistsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FileExists not implemented")
}
func (UnimplementedPeerServiceServer) FileSize(context.Context, *FileSizeRequest) (*FileSizeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FileSize not implemented")
}
func (UnimplementedPeerServiceServer) mustEmbedUnimplementedPeerServiceServer() {}

// UnsafePeerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PeerServiceServer will
// result in compilation errors.
type UnsafePeerServiceServer interface {
	mustEmbedUnimplementedPeerServiceServer()
}

func RegisterPeerServiceServer(s grpc.ServiceRegistrar, srv PeerServiceServer) {
	s.RegisterService(&PeerService_ServiceDesc, srv)
}

func _PeerService_ReadFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ReadFileRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PeerServiceServer).ReadFile(m, &peerServiceReadFileServer{stream})
}

type PeerService_ReadFileServer interface {
	Send(*FileChunk) error
	grpc.ServerStream
}

type peerServiceReadFileServer struct {
	grpc.ServerStream
}

func (x *peerServiceReadFileServer) Send(m *FileChunk) error {
	return x.ServerStream.SendMsg(m)
}

func _PeerService_WriteFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PeerServiceServer).WriteFile(&peerServiceWriteFileServer{stream})
}

type PeerService_WriteFileServer interface {
	SendAndClose(*WriteFileResponse) error
	Recv() (*WriteFileRequest, error)
	grpc.ServerStream
}

type peerServiceWriteFileServer struct {
	grpc.ServerStream
}

func (x *peerServiceWriteFileServer) SendAndClose(m *WriteFileResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *peerServiceWriteFileServer) Recv() (*WriteFileRequest, error) {
	m := new(WriteFileRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _PeerService_DeleteFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeerServiceServer).DeleteFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PeerService_DeleteFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeerServiceServer).DeleteFile(ctx, req.(*DeleteFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PeerService_FileExists_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FileExistsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeerServiceServer).FileExists(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PeerService_FileExists_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeerServiceServer).FileExists(ctx, req.(*FileExistsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PeerService_FileSize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FileSizeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeerServiceServer).FileSize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PeerService_FileSize_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeerServiceServer).FileSize(ctx, req.(*FileSizeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PeerService_ServiceDesc is the grpc.ServiceDesc for PeerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PeerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.PeerService",
	HandlerType: (*PeerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DeleteFile",
			Handler:    _PeerService_DeleteFile_Handler,
		},
		{
			MethodName: "FileExists",
			Handler:    _PeerService_FileExists_Handler,
		},
		{
			MethodName: "FileSize",
			Handler:    _PeerService_FileSize_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ReadFile",
			Handler:       _PeerService_ReadFile_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "WriteFile",
			Handler:       _PeerService_WriteFile_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "peer.proto",
}
